### ISSUE TITLE
QoL: 2 Enhancements for mass easy adding/changing of sprites

### ISSUE THREAD

**Issue by verisar** [ProgSys/pg_disatools#13]
Hello again, so ive decided to go ham on this to make as many sprites HD as i can, in doing so i will have to edit alot of sprite sheets.

QoL 1:(Easy to implement) Add an option the the sprite animation preview to move the sprite around to center it, now im not asking for full options of depth and what not just to center the bottom of the sprite in the middle of the shadow with the mouse.
![capture](https://user-images.githubusercontent.com/15370687/27603301-53396a7a-5b3b-11e7-98ae-65c25e75b10c.PNG)
This can also be done with clicking on the keyframe and using the arrow keys to move the sprite and then also using shift and ctrl to move anchor and offset so you wouldn't have to change them manually every little bit to get them perfect.

QoL 2:(Hard to implement) This would have to the hardest to implement but would be the absolute best.
Gimp has a feature where you can auto crop images which is great for sprite sheet editing where it will cut the image from the top left bottom and right of the image and get rid of space that has no color in it when you have a transparent background. 

So what would be awesome is if there was a button next to the new sprite button that autocrops the sprite doing the same thing working from the top left of the sheet to the right and bottom of the first set of images and then the next time you click it, it would null the already chosen sprite and work from the right of that till there are no more colors to chose from and work from the next row.

Now i know Number 2 is pretty pointless to add due to this being a hobby thing, but i must ask, if this tool was created and the sprite sheet editor was added, why are there no .sh files online of people already doing this? I did see that one from the youtube video/steam discussions but for one hes using the completely wrong leharl for the game hes using D2s i believe which in the grand scheme of things makes no sense since there are more male leharls then females.

Thanks again for these tools and if you dont feel the need just close and delete thread please. Have a good one.

**Comment by verisar** [comment]
Also like to say that if it does get easier to add these sprites my endgoal would be to try to work past the size limit by completely destroying the original sprite sheets besides the animations that cant be HD by re adding sprite sheets with only the needed sprites.

**Comment by ProgSys** [comment]
I will look into it as soon i have time, maybe this weekend but not sure. Busy with some deadlines and stuff. 
Actually the first one is harder than the second one. The reason is that the library that I use for the GUI rearly makes it hard to handle key inputs. Still it definitely would make life easier, so I will look into it.

About your second one, do you want to crop the cutout or the entire sprite sheet? The thing is the sprite sheet need to have a size with a power of two, so it can't be a random number. What I could add is a option to crop a cutout, but not sure how much this would realy help, as it would be better if the cutouts are uniform in size. In the meantime you can actually click and drop the size and position of a cutout by selecting the little white dots on the edges of the cutout border.

**Comment by verisar** [comment]
For the second option, ive been using gimp to make custom sprite sheets of 512x512 with compression to make the most of the size and make the images smaller data size. I know about moving and resizing the sprite select if thats what you are talking about.

**Comment by ProgSys** [comment]
I didn't fully understand QoL 2, but I think I added both functions as you wanted them. You can now use the **arrow key** to move the offset of a **selected keyframe** and if you use button modifiers to perform other actions:

- if **Control** is helt, then the anchor is moved
- if **Alt** is helt, then the anchor is moved relative to the position
- if **Shift** is helt, then you can rotate the keyframe with left and right

Just make sure the 3D preview is focused, so you may need to click on it, to make it work.

Also now you can 'Crop' a cutout, just right click it, and select 'Crop' in it's context menu.

You can get the new version on the main page (v0.7.8 alpha): https://github.com/ProgSys/pg_disatools

**Comment by verisar** [comment]
Yes perfect, the inport sprite right and other options and also the ability to use arrow keys are just whats needed thanks.

Only issue is that i dont know if its just me but i cant change the sprite color table id now or anything on that bar everytime it hit a number nothing happens.

**Comment by verisar** [comment]
Actually i cant edit any of the numbers.

**Comment by ProgSys** [comment]
Ups, just redownloaded the latest version, this should be fixed now. The 3D preview was stealing the keys from all other views. Make sure to click on the 3D preview to use the arrow keys.

**Comment by verisar** [comment]
Redownload the latest? If thats what you mean i tried to redownload from the link on the main page and its still the same.

**Comment by ProgSys** [comment]
I gess dropbox is kinda slow, it should be updated now ...

**Comment by verisar** [comment]
Alright looks good thanks again for the help. Time to get to work on this.

**Comment by ProgSys** [comment]
I released another version again. It fixes several bugs, there were possible crashes when you use 'Crop'.

Also I added a useful function to find all cutotus on a sprite sheet:
![auto_find_cutouts](https://user-images.githubusercontent.com/4257741/27763502-0ffc5554-5e85-11e7-9f4b-42a142aa7f4d.jpg)

**Comment by verisar** [comment]
Wow that is amazing, thanks for this.

**Comment by verisar** [comment]
Probably no way to fix this but. 


![capture](https://user-images.githubusercontent.com/15370687/27763746-1f0b1e4e-5e4f-11e7-942c-d651a7a556cd.PNG)

**Comment by verisar** [comment]
But other then that its absolutely fantastic you can move thru so many sets and animations pretty fast now.

**Comment by ProgSys** [comment]
Redownload the latest version, this should now be better handled. They will now be merged together if they overlap each other.

**Comment by ProgSys** [comment]
I am not sure though if it is a good idea to have different sized cutouts during a animation. It could look choppy ingame. But no idear.

**Comment by verisar** [comment]
I overlap images to make sure that they are the same character height and width before i set them so shouldnt be too much of an issue.
